# -*- coding: utf-8 -*-
"""Taller2_ZIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDw4-TpPlnQdbxeVGmy-AteJidaEOLDw
"""

#Librería requeridas
import pandas as pd # Librería para manejo y analisis de estructura de datos
import numpy as np # Librería para matrices y arrays multidimensionales de gran tamaño
import zipfile # Libreria para trabajar con formatos de extensión *ZIP
import os # Librería que proporciona una interfaz para interactuar con el sistema operativo
import datetime # Librería que proporciona funciones para trabajar con fechas y horas

"""#Consultar el archivo ZIP cargado en el entorno web"""

if zipfile.is_zipfile("Datos_MedidoresAgua.zip"):
    with zipfile.ZipFile("Datos_MedidoresAgua.zip", "r") as archive:
        archive.printdir()
else:
    print("File is not a zip file")

#Extraer información de un solo conjunto de datos
with zipfile.ZipFile("Datos_MedidoresAgua.zip", mode="r") as archive:
    info = archive.getinfo("Datos_MedidoresAgua/ConjuntoDatos_MedidoresAgua/ConjuntoDatos_1_50.txt")

info.file_size #Información del conjunto de datos en tamaño en bytes del archivo original

info.compress_size #Información del conjunto de datos en tamaño en bytes del archivo comprimido

info.filename #Infomración del nombre del conjunto de datos

info.date_time #Información de modificación del archivo

#Extraer información de todos los conjuntos de datos en el archivo *ZIP
with zipfile.ZipFile("Datos_MedidoresAgua.zip", mode="r") as archive:
    for info in archive.infolist():
        print(f"Filename: {info.filename}")
        print(f"Modified: {datetime.datetime(*info.date_time)}")
        print(f"Normal size: {info.file_size} bytes")
        print(f"Compressed size: {info.compress_size} bytes")
        print("-" * 20)

#Lectura rápida con secuencia bytes "b" de un conjunto de datos del archivo sin extraerlo
with zipfile.ZipFile("Datos_MedidoresAgua.zip", mode="r") as archive:
    for line in archive.read("Datos_MedidoresAgua/ConjuntoDatos_MedidoresAgua/ConjuntoDatos_1_50.txt").split(b"\n"):
        print(line)

# Extraccion del formato *xslx del archivo *ZIP y descompresión
with zipfile.ZipFile("Datos_MedidoresAgua.zip", mode="r") as archive:
    for file in archive.namelist():
      if file.endswith(".xlsx"):
        archive.extract(file, "/content/Diccionarios")

# Extraccion del formato *txt del archivo *ZIP y descompresión
with zipfile.ZipFile("Datos_MedidoresAgua.zip", mode="r") as archive:
    for file in archive.namelist():
      if file.endswith(".txt"):
        archive.extract(file, "/content/ConjuntosDatos")

"""---

#Tranformación de un formato *TXT a dataframe y exportación a formato *XLSX
"""

# Ruta del archivo .txt
file_path = "/content/ConjuntosDatos/Datos_MedidoresAgua/ConjuntoDatos_MedidoresAgua/ConjuntoDatos_1_50.txt"
# Leer el archivo .txt en un DataFrame
# Cambia 'sep' según el delimitador del archivo ','
df = pd.read_csv(file_path, sep=",")  # Cambia ',' por '\t' si es tabulado

# Mostrar las primeras filas del DataFrame
print("Contenido del DataFrame:")
print(df)

#Guardar el DataFrame en otro formato Excel
df.to_excel("CD_1_50.xlsx", index=False)
print("\nEl DataFrame se ha guardado como 'ConjuntoDatos_1_50.xlsx'.")

# Ruta del archivo .txt
file_path = "/content/ConjuntosDatos/Datos_MedidoresAgua/ConjuntoDatos_MedidoresAgua/ConjuntoDatos_2_100.txt"
# Leer el archivo .txt en un DataFrame
# Cambia 'sep' según el delimitador del archivo ','
df2 = pd.read_csv(file_path, sep=",")  # Cambia ',' por '\t' si es tabulado

# Mostrar las primeras filas del DataFrame
print("Contenido del DataFrame:")
print(df2)

#Guardar el DataFrame en otro formato Excel
df2.to_excel("CD_2_100.xlsx", index=False)
print("\nEl DataFrame se ha guardado como 'ConjuntoDatos_2_100.xlsx'.")

"""---

#Exploración del conjunto de datos

Conjunto de datos 1
"""

#Cargar el archivo XLSX en un DataFrame y configurar la ruta
df = pd.read_excel("/content/CD_1_50.xlsx")

#Explorar el dataframe nombrado por las 10 primeras filas
print(df.head(10))

#Consultar la estrcutura, cantidad de las filas y columnas
#Forma del DataFrame (filas, columnas)
filas, columnas = df.shape

#Nombres de columnas
nombres_columnas = df.columns.tolist()

#Índices del DataFrame
indices = df.index.tolist()

print("Forma del DataFrame:")
print("Filas:", filas)
print("Columnas:", columnas)

print("\nNombres de las columnas:")
print(nombres_columnas)

print("\nÍndices del DataFrame:")
print(indices)

"""Conjunto de datos 2"""

#Cargar el archivo XLSX en un DataFrame y configurar la ruta
df2 = pd.read_excel("/content/CD_2_100.xlsx")

#Explorar el dataframe nombrado por las 10 primeras filas
print(df2.head(10))

#Adiccionar el nombre de la columna en el encabezado
df2 = df2.set_axis(['No', 'Water Meter ID', 'Reading ID', 'Reading Value', 'Reading Date', 'Previous Reading Value', 'Previous Reading Date', 'Reading Frequency', 'Reader ID', 'Type of Contract', 'Reading Validity', 'Certification on the ERP', 'Final Billing', 'Reason for Reading']
, axis='columns')

#Consultar la estrcutura, cantidad de las filas y columnas
#Forma del DataFrame (filas, columnas)
filas, columnas = df2.shape

#Nombres de columnas
nombres_columnas = df2.columns.tolist()

#Índices del DataFrame
indices = df2.index.tolist()

print("Forma del DataFrame:")
print("Filas:", filas)
print("Columnas:", columnas)

print("\nNombres de las columnas:")
print(nombres_columnas)

print("\nÍndices del DataFrame:")
print(indices)

#Validación del ajuste en el dataframe nombrado por las 10 primeras filas
print(df2.head(3))

#Forma de consultar la cantidad de filas y columnas
num_filas = len(df2)
num_columnas = len(df2.columns)

print(f"Filas: {num_filas}, Columnas: {num_columnas}")

#Exploración por tipo de variable en las columnas del conjunto de datos
#Columnas numéricas
columnas_numericas = df2.select_dtypes(include=['int64', 'float64']).columns
print("Columnas numéricas:")
print(columnas_numericas)

#Columnas categóricas
columnas_categoricas = df.select_dtypes(include=['object', 'category']).columns
print("Columnas categóricas:")
print(columnas_categoricas)

"""Unificar los datasets"""

#Método de unión
df_unificado = pd.concat([df, df2], ignore_index=True)

#Consultar la estrcutura, cantidad de las filas y columnas
#Forma del DataFrame (filas, columnas)
filas, columnas = df_unificado.shape

#Nombres de columnas
nombres_columnas = df_unificado.columns.tolist()

#Índices del DataFrame
indices = df_unificado.index.tolist()

print("Forma del DataFrame:")
print("Filas:", filas)
print("Columnas:", columnas)

print(df_unificado.head(10))

#Guardar el DataFrame en otro formato Excel
df_unificado.to_excel("CD_unificado_500.xlsx", index=False)
print("\nEl DataFrame se ha guardado como 'CD_unificado_500.xlsx'.")

"""---

#Limpieza de datos
"""

# Solución alternativa con ydata-profiling (recomendado)
!pip install ydata-profiling

from ydata_profiling import ProfileReport
import pandas as pd

# Cargar tus datos
df_unificado = pd.read_excel('/content/CD_unificado_500.xlsx')  # Reemplaza con tu archivo

# Generar reporte EDA
profile = ProfileReport(df_unificado, title="Reporte EDA")
profile.to_notebook_iframe()  # Para mostrar en notebook
profile.to_file("reporte_eda.html")  # Para guardar como HTML